// Interface automatically generated by schemas-to-ts

export enum Variant {
  Classic = 'classic',
  Solid = 'solid',
  Soft = 'soft',
  Surface = 'surface',
  Outline = 'outline',
  Ghost = 'ghost',
}

export interface CtaButton {
  id: number;
  text: string;
  url: string;
  variant: Variant;
}
export interface CtaButton_Plain {
  id: number;
  text: string;
  url: string;
  variant: Variant;
}

export interface CtaButton_NoRelations {
  id: number;
  text: string;
  url: string;
  variant: Variant;
}
