// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/interfaces/Media';

export interface Hero {
  title?: string;
  description?: string;
  backgroundImage?: { data: Media };
}
export interface Hero_Plain {
  title?: string;
  description?: string;
  backgroundImage?: Media;
}

export interface Hero_NoRelations {
  title?: string;
  description?: string;
  backgroundImage?: number;
}
