// Interface automatically generated by schemas-to-ts

import { Category } from '../../../api/category/content-types/category/category';
import { Course } from '../../../api/course/content-types/course/course';
import { Cuisine } from '../../../api/cuisine/content-types/cuisine/cuisine';
import { Diet } from '../../../api/diet/content-types/diet/diet';
import { Ingredient } from '../../../api/ingredient/content-types/ingredient/ingredient';
import { MealType } from '../../../api/meal-type/content-types/meal-type/meal-type';
import { Method } from '../../../api/method/content-types/method/method';
import { Season } from '../../../api/season/content-types/season/season';
import { Category_Plain } from '../../../api/category/content-types/category/category';
import { Course_Plain } from '../../../api/course/content-types/course/course';
import { Cuisine_Plain } from '../../../api/cuisine/content-types/cuisine/cuisine';
import { Diet_Plain } from '../../../api/diet/content-types/diet/diet';
import { Ingredient_Plain } from '../../../api/ingredient/content-types/ingredient/ingredient';
import { MealType_Plain } from '../../../api/meal-type/content-types/meal-type/meal-type';
import { Method_Plain } from '../../../api/method/content-types/method/method';
import { Season_Plain } from '../../../api/season/content-types/season/season';

export interface RecipeCarousel {
  limit: number;
  title?: string;
  categories: { data: Category[] };
  courses: { data: Course[] };
  cuisines: { data: Cuisine[] };
  diets: { data: Diet[] };
  ingredients: { data: Ingredient[] };
  mealTypes: { data: MealType[] };
  methods: { data: Method[] };
  seasons: { data: Season[] };
}
export interface RecipeCarousel_Plain {
  limit: number;
  title?: string;
  categories: Category_Plain[];
  courses: Course_Plain[];
  cuisines: Cuisine_Plain[];
  diets: Diet_Plain[];
  ingredients: Ingredient_Plain[];
  mealTypes: MealType_Plain[];
  methods: Method_Plain[];
  seasons: Season_Plain[];
}

export interface RecipeCarousel_NoRelations {
  limit: number;
  title?: string;
  categories: number[];
  courses: number[];
  cuisines: number[];
  diets: number[];
  ingredients: number[];
  mealTypes: number[];
  methods: number[];
  seasons: number[];
}

