// Interface automatically generated by schemas-to-ts

export interface RecipeCarousel {
  limit: number;
  title?: string;
}
export interface RecipeCarousel_Plain {
  limit: number;
  title?: string;
}

export interface RecipeCarousel_NoRelations {
  limit: number;
  title?: string;
}

