// Interface automatically generated by schemas-to-ts

export interface RichText {
  blocks: any;
}
export interface RichText_Plain {
  blocks: any;
}

export interface RichText_NoRelations {
  blocks: any;
}

