// Interface automatically generated by schemas-to-ts

export interface HomePageItem {
  label: string;
}
export interface HomePageItem_Plain {
  label: string;
}

export interface HomePageItem_NoRelations {
  label: string;
}

