// Interface automatically generated by schemas-to-ts

export interface RecipeSearchPageItem {
  label?: string;
}
export interface RecipeSearchPageItem_Plain {
  label?: string;
}

export interface RecipeSearchPageItem_NoRelations {
  label?: string;
}

