version: '3'

services:
  recipes-api:
    container_name: recipes-api
    image: strapi:4.15.0
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.production
      args:
        API_ADMIN_JWT_SECRET: ${API_ADMIN_JWT_SECRET}
        API_APP_KEYS: ${API_APP_KEYS}
        API_HOST: ${API_HOST}
        API_JWT_SECRET: ${API_JWT_SECRET}
        API_PORT: ${API_PORT}
        API_TOKEN_SALT: ${API_TOKEN_SALT}
        API_TRANSFER_TOKEN_SALT: ${API_TRANSFER_TOKEN_SALT}
        DB_HOST: ${DB_HOST}
        DB_NAME: ${DB_NAME}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_PORT: ${DB_PORT}
        DB_USERNAME: ${DB_USERNAME}
        SEARCH_HOST: ${SEARCH_HOST}
        SEARCH_MASTER_KEY: ${SEARCH_MASTER_KEY}
        SEARCH_PORT: ${SEARCH_PORT}
        SEARCH_PROTOCOL: ${SEARCH_PROTOCOL}
    volumes:
      - ./apps/api/config:/app/apps/api/config
      - ./apps/api/public/uploads:/app/apps/api/public/uploads
      - ./apps/api/src:/app/apps/api/src
    restart: unless-stopped
    ports:
      - '1337:1337'
    networks:
      - recipes-network
    depends_on:
      - recipes-db
      - recipes-search

  recipes-db:
    container_name: recipes-db
    platform: linux/amd64
    image: postgres:14.0-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    volumes:
      - recipes-data:/var/lib/postgresql/data/
    restart: unless-stopped
    ports:
      - '5432:5432'
    networks:
      - recipes-network

  recipes-search:
    container_name: recipes-search
    image: getmeili/meilisearch:v1.4.1
    command: meilisearch
    environment:
      MEILI_MASTER_KEY: ${SEARCH_MASTER_KEY}
    volumes:
      - ../meilisearch/data.ms:/data.ms
    restart: unless-stopped
    ports:
      - '7700:7700'
    networks:
      - recipes-network

  recipes-web:
    container_name: recipes-web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.production
      args:
        API_HOST: ${API_HOST}
        API_PORT: ${API_PORT}
        API_PROTOCOL: ${API_PROTOCOL}
        API_TOKEN: ${API_TOKEN}
        NEXT_TELEMETRY_DISABLED: ${NEXT_TELEMETRY_DISABLED}
        SEARCH_HOST: ${SEARCH_HOST}
        SEARCH_MASTER_KEY: ${SEARCH_MASTER_KEY}
        SEARCH_PORT: ${SEARCH_PORT}
        SEARCH_PROTOCOL: ${SEARCH_PROTOCOL}
        WEB_BASE_URL: ${WEB_BASE_URL}
    volumes:
      - ./apps/web/messages:/app/apps/web/messages
      - ./apps/web/public:/app/apps/web/public
      - ./apps/web/src:/app/apps/web/src
      - ./packages/api-client/src:/app/packages/api-client/src
      - ./packages/ui/src:/app/packages/ui/src
    restart: always
    ports:
      - 3000:3000
    networks:
      - recipes-network

volumes:
  recipes-data:

networks:
  recipes-network:
    driver: bridge
