// Interface automatically generated by schemas-to-ts

export enum Attribute {
  Categories = 'categories',
  Courses = 'courses',
  Cuisines = 'cuisines',
  Diets = 'diets',
  MainIngredients = 'mainIngredients',
  MealTypes = 'mealTypes',
  Methods = 'methods',
  Seasons = 'seasons',
}

export interface RecipeSearchSelectFilter {
  label: string;
  multiple: boolean;
  attribute: Attribute;
}
export interface RecipeSearchSelectFilter_Plain {
  label: string;
  multiple: boolean;
  attribute: Attribute;
}

export interface RecipeSearchSelectFilter_NoRelations {
  label: string;
  multiple: boolean;
  attribute: Attribute;
}
