// Interface automatically generated by schemas-to-ts

export enum Name {
  Category = 'category',
  Course = 'course',
  Cuisine = 'cuisine',
  Diet = 'diet',
  Ingredient = 'ingredient',
  MealType = 'mealType',
  Method = 'method',
  Season = 'season',}

export interface SelectFilter {
  label: string;
  multiple: boolean;
  name: Name;
}
export interface SelectFilter_Plain {
  label: string;
  multiple: boolean;
  name: Name;
}

export interface SelectFilter_NoRelations {
  label: string;
  multiple: boolean;
  name: Name;
}

