// Interface automatically generated by schemas-to-ts

export enum Attribute {
  Categories = 'categories',
  Courses = 'courses',
  Cuisines = 'cuisines',
  Diets = 'diets',
  Ingredients = 'ingredients',
  MealTypes = 'mealTypes',
  Methods = 'methods',
  Seasons = 'seasons',}

export interface SelectFilter {
  label: string;
  multiple: boolean;
  attribute: Attribute;
}
export interface SelectFilter_Plain {
  label: string;
  multiple: boolean;
  attribute: Attribute;
}

export interface SelectFilter_NoRelations {
  label: string;
  multiple: boolean;
  attribute: Attribute;
}

