// Interface automatically generated by schemas-to-ts

export enum Value {
  CreatedAtAsc = 'created-at-asc',
  CreatedAtDesc = 'created-at-desc',
  TitleAsc = 'title-asc',
  TitleDesc = 'title-desc',}

export interface SortOrderOption {
  name: string;
  value: Value;
}
export interface SortOrderOption_Plain {
  name: string;
  value: Value;
}

export interface SortOrderOption_NoRelations {
  name: string;
  value: Value;
}

