// Interface automatically generated by schemas-to-ts

import { SortOrderOption } from './SortOrderOption';
import { SortOrderOption_Plain } from './SortOrderOption';
import { SortOrderOption_NoRelations } from './SortOrderOption';

export interface SortOrder {
  label: string;
  options: SortOrderOption[];
}
export interface SortOrder_Plain {
  label: string;
  options: SortOrderOption_Plain[];
}

export interface SortOrder_NoRelations {
  label: string;
  options: SortOrderOption_NoRelations[];
}

