// Interface automatically generated by schemas-to-ts

import { Comment } from '../../../comment/content-types/comment/comment';
import { Recipe } from '../../../recipe/content-types/recipe/recipe';
import { Comment_Plain } from '../../../comment/content-types/comment/comment';
import { Recipe_Plain } from '../../../recipe/content-types/recipe/recipe';
import { AdminPanelRelationPropertyModification } from '../../../../common/interfaces/AdminPanelRelationPropertyModification';

export interface Rating {
  id: number;
  attributes: {
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    score: number;
    userId: string;
    comment?: { data: Comment };
    recipe?: { data: Recipe };
  };
}
export interface Rating_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  score: number;
  userId: string;
  comment?: Comment_Plain;
  recipe?: Recipe_Plain;
}

export interface Rating_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  score: number;
  userId: string;
  comment?: number;
  recipe?: number;
}

export interface Rating_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  score: number;
  userId: string;
  comment?: AdminPanelRelationPropertyModification<Comment_Plain>;
  recipe?: AdminPanelRelationPropertyModification<Recipe_Plain>;
}
