// Interface automatically generated by schemas-to-ts

import { Recipe } from '../../../recipe/content-types/recipe/recipe';
import { Recipe_Plain } from '../../../recipe/content-types/recipe/recipe';
import { AdminPanelRelationPropertyModification } from '../../../../common/interfaces/AdminPanelRelationPropertyModification';

export interface MealType {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name: string;
    slug: string;
    recipes?: { data: Recipe[] };
    locale: string;
    localizations?: { data: MealType[] };
  };
}
export interface MealType_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  slug: string;
  recipes?: Recipe_Plain[];
  locale: string;
  localizations?: MealType[];
}

export interface MealType_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  slug: string;
  recipes?: number[];
  locale: string;
  localizations?: MealType[];
}

export interface MealType_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  slug: string;
  recipes?: AdminPanelRelationPropertyModification<Recipe_Plain>;
  locale: string;
  localizations?: MealType[];
}
