// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/interfaces/Media';

export interface Metadata {
  title?: string;
  description?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImage?: { data: Media };
}
export interface Metadata_Plain {
  title?: string;
  description?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImage?: Media;
}

export interface Metadata_NoRelations {
  title?: string;
  description?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImage?: number;
}
