// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/interfaces/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/interfaces/AdminPanelRelationPropertyModification';

export interface Recipe {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    slug: string;
    image?: { data: Media };
    description?: string;
    locale: string;
    localizations?: { data: Recipe[] };
  };
}
export interface Recipe_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  slug: string;
  image?: Media;
  description?: string;
  locale: string;
  localizations?: Recipe[];
}

export interface Recipe_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  slug: string;
  image?: number;
  description?: string;
  locale: string;
  localizations?: Recipe[];
}

export interface Recipe_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  slug: string;
  image?: AdminPanelRelationPropertyModification<Media>;
  description?: string;
  locale: string;
  localizations?: Recipe[];
}
