// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/interfaces/Media';
import { Category } from '../../../category/content-types/category/category';
import { MealType } from '../../../meal-type/content-types/meal-type/meal-type';
import { Course } from '../../../course/content-types/course/course';
import { Diet } from '../../../diet/content-types/diet/diet';
import { Season } from '../../../season/content-types/season/season';
import { Method } from '../../../method/content-types/method/method';
import { Ingredient } from '../../../ingredient/content-types/ingredient/ingredient';
import { Category_Plain } from '../../../category/content-types/category/category';
import { MealType_Plain } from '../../../meal-type/content-types/meal-type/meal-type';
import { Course_Plain } from '../../../course/content-types/course/course';
import { Diet_Plain } from '../../../diet/content-types/diet/diet';
import { Season_Plain } from '../../../season/content-types/season/season';
import { Method_Plain } from '../../../method/content-types/method/method';
import { Ingredient_Plain } from '../../../ingredient/content-types/ingredient/ingredient';
import { AdminPanelRelationPropertyModification } from '../../../../common/interfaces/AdminPanelRelationPropertyModification';

export interface Recipe {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    slug: string;
    image?: { data: Media };
    description?: string;
    categories?: { data: Category[] };
    mealTypes?: { data: MealType[] };
    courses?: { data: Course[] };
    diets?: { data: Diet[] };
    seasons?: { data: Season[] };
    methods?: { data: Method[] };
    ingredients?: { data: Ingredient[] };
    locale: string;
    localizations?: { data: Recipe[] };
  };
}
export interface Recipe_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  slug: string;
  image?: Media;
  description?: string;
  categories?: Category_Plain[];
  mealTypes?: MealType_Plain[];
  courses?: Course_Plain[];
  diets?: Diet_Plain[];
  seasons?: Season_Plain[];
  methods?: Method_Plain[];
  ingredients?: Ingredient_Plain[];
  locale: string;
  localizations?: Recipe[];
}

export interface Recipe_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  slug: string;
  image?: number;
  description?: string;
  categories?: number[];
  mealTypes?: number[];
  courses?: number[];
  diets?: number[];
  seasons?: number[];
  methods?: number[];
  ingredients?: number[];
  locale: string;
  localizations?: Recipe[];
}

export interface Recipe_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  slug: string;
  image?: AdminPanelRelationPropertyModification<Media>;
  description?: string;
  categories?: AdminPanelRelationPropertyModification<Category_Plain>;
  mealTypes?: AdminPanelRelationPropertyModification<MealType_Plain>;
  courses?: AdminPanelRelationPropertyModification<Course_Plain>;
  diets?: AdminPanelRelationPropertyModification<Diet_Plain>;
  seasons?: AdminPanelRelationPropertyModification<Season_Plain>;
  methods?: AdminPanelRelationPropertyModification<Method_Plain>;
  ingredients?: AdminPanelRelationPropertyModification<Ingredient_Plain>;
  locale: string;
  localizations?: Recipe[];
}
