// Interface automatically generated by schemas-to-ts

import { Rating } from '../../../rating/content-types/rating/rating';
import { Recipe } from '../../../recipe/content-types/recipe/recipe';
import { Rating_Plain } from '../../../rating/content-types/rating/rating';
import { Recipe_Plain } from '../../../recipe/content-types/recipe/recipe';
import { AdminPanelRelationPropertyModification } from '../../../../common/interfaces/AdminPanelRelationPropertyModification';

export interface Comment {
  id: number;
  attributes: {
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    name: string;
    comment: string;
    userId: string;
    rating?: { data: Rating };
    recipe?: { data: Recipe };
    locale: string;
    localizations?: { data: Comment[] };
  };
}
export interface Comment_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  name: string;
  comment: string;
  userId: string;
  rating?: Rating_Plain;
  recipe?: Recipe_Plain;
  locale: string;
  localizations?: Comment[];
}

export interface Comment_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  name: string;
  comment: string;
  userId: string;
  rating?: number;
  recipe?: number;
  locale: string;
  localizations?: Comment[];
}

export interface Comment_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  name: string;
  comment: string;
  userId: string;
  rating?: AdminPanelRelationPropertyModification<Rating_Plain>;
  recipe?: AdminPanelRelationPropertyModification<Recipe_Plain>;
  locale: string;
  localizations?: Comment[];
}
