// Interface automatically generated by schemas-to-ts

import { AdminPanelRelationPropertyModification } from '../../../../common/interfaces/AdminPanelRelationPropertyModification';
import { User, User_Plain } from '../../../../common/interfaces/User';
import {
  Rating,
  Rating_Plain,
} from '../../../rating/content-types/rating/rating';
import {
  Recipe,
  Recipe_Plain,
} from '../../../recipe/content-types/recipe/recipe';

export interface Comment {
  id: number;
  attributes: {
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    name: string;
    comment: string;
    userId: string;
    rating?: { data: Rating };
    recipe?: { data: Recipe };
    locale: string;
    localizations?: { data: Comment[] };
    user?: { data: User };
  };
}
export interface Comment_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  name: string;
  comment: string;
  userId: string;
  rating?: Rating_Plain;
  recipe?: Recipe_Plain;
  locale: string;
  localizations?: Comment[];
  user?: User_Plain;
}

export interface Comment_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  name: string;
  comment: string;
  userId: string;
  rating?: number;
  recipe?: number;
  locale: string;
  localizations?: Comment[];
  user?: number;
}

export interface Comment_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  name: string;
  comment: string;
  userId: string;
  rating?: AdminPanelRelationPropertyModification<Rating_Plain>;
  recipe?: AdminPanelRelationPropertyModification<Recipe_Plain>;
  locale: string;
  localizations?: Comment[];
  user?: AdminPanelRelationPropertyModification<User_Plain>;
}
