// Interface automatically generated by schemas-to-ts

export interface HomePage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    content?: any;
    locale: string;
    localizations?: { data: HomePage[] };
  };
}
export interface HomePage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  content?: any;
  locale: string;
  localizations?: HomePage[];
}

export interface HomePage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  content?: any;
  locale: string;
  localizations?: HomePage[];
}

export interface HomePage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  content?: any;
  locale: string;
  localizations?: HomePage[];
}
