// Interface automatically generated by schemas-to-ts

export interface Cuisine {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name: string;
    slug: string;
    locale: string;
    localizations?: { data: Cuisine[] };
  };
}
export interface Cuisine_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  slug: string;
  locale: string;
  localizations?: Cuisine[];
}

export interface Cuisine_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  slug: string;
  locale: string;
  localizations?: Cuisine[];
}

export interface Cuisine_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  slug: string;
  locale: string;
  localizations?: Cuisine[];
}
