// Interface automatically generated by schemas-to-ts

import { SortOrder } from '../../../../components/recipe-search/interfaces/SortOrder';
import { Metadata } from '../../../../components/page/interfaces/Metadata';
import { SortOrder_Plain } from '../../../../components/recipe-search/interfaces/SortOrder';
import { Metadata_Plain } from '../../../../components/page/interfaces/Metadata';
import { SortOrder_NoRelations } from '../../../../components/recipe-search/interfaces/SortOrder';
import { Metadata_NoRelations } from '../../../../components/page/interfaces/Metadata';

export interface RecipeSearchPage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    filters: any;
    sortOrder?: SortOrder;
    pageSize: number;
    metadata?: Metadata;
    locale: string;
    localizations?: { data: RecipeSearchPage[] };
  };
}
export interface RecipeSearchPage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  filters: any;
  sortOrder?: SortOrder_Plain;
  pageSize: number;
  metadata?: Metadata_Plain;
  locale: string;
  localizations?: RecipeSearchPage[];
}

export interface RecipeSearchPage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  filters: any;
  sortOrder?: SortOrder_NoRelations;
  pageSize: number;
  metadata?: Metadata_NoRelations;
  locale: string;
  localizations?: RecipeSearchPage[];
}

export interface RecipeSearchPage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  filters: any;
  sortOrder?: SortOrder_Plain;
  pageSize: number;
  metadata?: Metadata_Plain;
  locale: string;
  localizations?: RecipeSearchPage[];
}
