// Interface automatically generated by schemas-to-ts

export interface IngredientItem {
  id: number;
  amount?: number;
  unit?: string;
  content: any;
  altAmount?: number;
  altUnit?: string;
}
export interface IngredientItem_Plain {
  id: number;
  amount?: number;
  unit?: string;
  content: any;
  altAmount?: number;
  altUnit?: string;
}

export interface IngredientItem_NoRelations {
  id: number;
  amount?: number;
  unit?: string;
  content: any;
  altAmount?: number;
  altUnit?: string;
}
