// Interface automatically generated by schemas-to-ts

import {
  IngredientItem,
  IngredientItem_NoRelations,
  IngredientItem_Plain,
} from './IngredientItem';

export interface IngredientList {
  title?: string;
  items: IngredientItem[];
}
export interface IngredientList_Plain {
  title?: string;
  items: IngredientItem_Plain[];
}

export interface IngredientList_NoRelations {
  title?: string;
  items: IngredientItem_NoRelations[];
}
