// Interface automatically generated by schemas-to-ts

export interface IngredientItem {
  amount?: number;
  unit?: string;
  content: any;
}
export interface IngredientItem_Plain {
  amount?: number;
  unit?: string;
  content: any;
}

export interface IngredientItem_NoRelations {
  amount?: number;
  unit?: string;
  content: any;
}

