// Interface automatically generated by schemas-to-ts

export interface InstructionItem {
  content: any;
}
export interface InstructionItem_Plain {
  content: any;
}

export interface InstructionItem_NoRelations {
  content: any;
}

